language: node_js
node_js: stable
 
install:
  - npm install hexo -g
  - npm install
 
 
script:
  - hexo g
 
after_script:
  - git init
  - git config user.name "mlei"
  - git config user.email "773984215@qq.com"
  - git add .
  - git commit -m "auto sync repository"
  - git push --force --quiet "https://${deploy_gitlab}@gitlab.com/mlei/mlei.git" hexo: hexo
  - cd ./public
  - git init
  - git config user.name "leim"
  - git config user.email "z@menglei.tk"
  - git add .
  - git commit -m "auto update docs by travis ci"
  - git push --force --quiet "https://${deploy_github_public_repo}@github.com/leim/leim.github.io.git" master:master
 
branches:
  only:
    - hexo

